### ISSUE TITLE
请教问题

### ISSUE THREAD

**Issue by alwaysWanYing** [JaminQ/wedding-invitation#2]
前辈你好，问什么小程序上线一直不通过呢，提示：你好，你的小程序涉及视频服务，属个人主体小程序未开放类目，建议申请企业主体小程序。 你好，你的小程序页面含【留言】tab，属个人主体小程序未开放类目，建议申请企业主体小程序并选择社交-社区/论坛类目。
question：有什么解决办法吗，我也想有个彩蛋视频功能

**Comment by JaminQ** [comment]
你是用视频号视频吗？还是video组件贴的视频？

我用的是视频号视频，实测应该不会被卡审核才对
