### ISSUE TITLE
问一下 配置了onShareAppMessage和onShareTimeline怎么还是不能分享到朋友圈

### ISSUE THREAD

**Issue by ty091015** [JaminQ/wedding-invitation#3]

**Comment by JaminQ** [comment]
备案以及认证都搞了吗？好像出了新规，现在如果没有认证的话，就封掉分享的能力，然后认证要30元

**Comment by ty091015** [comment]
好的，我先试试认证

**Comment by ty091015** [comment]
还有那个评论  也过不了审核 需要注释掉才能通过，有什么方法？

**Comment by JaminQ** [comment]
评论过不了审核有说原因吗？

**Comment by ty091015** [comment]
![image](https://github.com/JaminQ/wedding-invitation/assets/101166635/c0e9bda7-2943-4e6b-bdb1-8ab0a41b21f2)
就是说的有自定义的文字 不能通过

**Comment by JaminQ** [comment]
还真没有在审核的时候遇到过这个问题，其他几位用了这个代码的小伙伴也没遇到过

如果真的运气不好遇到了，兴许你可以试试这样，加个后台开关标记位来控制祝福语的相关逻辑，提交审核的时候在后台把开关关掉，审核通过了再把开关开回去（盲猜这个审核不会去仔细研究你的代码，毕竟不是什么重点关注小程序）

**Comment by ty091015** [comment]
感谢  1. 加了一个暗门  审核就通过了 2. 需要认证才能被分享

**Comment by JaminQ** [comment]
新婚快乐🎉(´∀｀)🎈
