### ISSUE TITLE
肯定比婚贝上生成的自由度高太多了，就是收不了礼金了哈哈哈哈

### ISSUE THREAD

**Issue by MikaKaiSun** [JaminQ/wedding-invitation#8]

**Comment by JaminQ** [comment]
这倒是我觉得最不需要实现的功能了。

我觉得礼金这东西吧，还是线下见面的时候亲手给才最有意思，线上操作过于冰冷，少了些人情味。

而且，如果我的朋友真的想要通过线上途径给我礼金，可以直接微信红包或者微信转账，真没必要通过小程序来给。
